# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.tongkun.tech
date_format: "ordinal"
title: 人在码途
subtitle: "人在码途"
description: "佟堃的个人博客"
keywords: 人在码途,码途,佟堃,tongkun,matu
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Tong Kun
organization: tongkun.tech
organization_url: http://blog.tongkun.tech
github_username: tk1990
location: Beijing, China
email: tongk1990@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  # -
  #   href: /wiki/
  #   label: 维基

  # -
  #   href: /links/
  #   label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: tk1990/tk1990.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: tk1990
    repo: blog-comments
    oauth:
        client_id: e03260401c274f4211c3
        client_secret: 97d5e9414c12bbc0787b11091d4fb74fa610777f5
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: tk1990
    repo: blog-comments
    clientID: e03260401c274f4211c3
    clientSecret: 97d5e9414c12bbc0787b11091d4fb74fa610777f5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
